name: Deploy serverless app

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            
            - name: Setup Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            
            - name: Install dependencies
              run: npm install
            
            - name: Serverless Deployment
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: npx serverless deploy